### ISSUE TITLE
Erreur sur A0 et B0 en ON/OFF

### ISSUE THREAD

**Issue by Cyrixo** [nono1024/Rasp-mcp23017#1]
Bonjour,
Tout a d'abord, superbe projet.
Je rencontre une erreur ( : undefined ) sur le ON/OFF des ports A0 et B0 depuis la page "accueil" et "relais". Le mode fugitif fonctionne bien sur ces deux ports.
N'étant pas codeur, je ne sais pas ou regarder pour corriger cette erreur.
Je me tiens à votre disposition pour toutes demandes d'informations, commandes....
Cordialement.

**Comment by nono1024** [comment]
Salut !
Oui en effet désolé, une petite erreur dans mon code, j'avais oublié de "pull" la correction....
Je viens de le corriger de suite, si tu re-clone le projet ça devrait le faire.
Et pense à sauvegarder les xml si tu garder ta conf.
++

**Comment by Cyrixo** [comment]
Merci, ça fonctionne.
@+
